plugins {
    id 'java'
    id 'application'
    id 'io.freefair.lombok' version '9.2.0'
}

repositories {
    mavenCentral()
}

lombok {
    version = lombok_version
}

application {
    mainClass = 'net.cjsah.slimefinder.Main'
}

jar {
    from("LICENSE")

    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    it.options.release = 21
}