plugins {
    id 'java'
    id 'application'
    id 'io.freefair.lombok' version '9.2.0'
    id 'com.gradleup.shadow' version '9.4.0'
}

application {
    mainClass = 'net.cjsah.slimefinder.Main'
}

repositories {
    mavenCentral()
}

lombok {
    version = lombok_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    it.options.release = 21
}